hawk:
  ai:
    enabled: true
    features:
      piece_count_matching: true
  sampling:
    enabled: false
    rate: 0.1
  subset:
    enabled: true
    products:
      variants:
#        - LABEDA_80_MM_WHEELS
        - UNDERCOVER_80_MM_WHEELS
        - UNDERCOVER_110_MM_WHEELS

spring:
  banner:
    location: classpath:ehawk-banner.txt
  liquibase:
    defaultSchema: merchandise_db
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hypersistence:
        utils:
          jackson:
            object:
              mapper: "io.irw.hawk.entity.type.CustomObjectMapperSupplier"
  datasource:
    url: ${hawk.db.url}
    username: ${hawk.db.username}
    password: ${hawk.db.password}
logging:
  level:
    com:
      theokanning:
        openai: TRACE
    io:
      irw:
        hawk: DEBUG
    org:
      hibernate:
        SQL: INFO
      springframework: INFO
      springframework.web.client.RestTemplate: TRACE

